name: validate-python-headers
author: frgfm
description: Validate the copyright & license references in the headers of your Python files
branding:
  icon: check-square
  color: blue

inputs:
  owner:
    description: 'Name of the copyright owner'
    required: true
  starting-year:
    description: 'Starting year of your project'
    required: true
  license:
    # https://spdx.org/licenses/
    description: 'License of your project'
    required: false
    default: null
  folders:
    description: 'Folders to inspect'
    required: false
    default: '.'
  ignore-files:
    description: 'Files to ignore'
    required: false
    default: '__init__.py'
  ignore-folders:
    description: 'Folders to ignore'
    required: false
    default: '.github/'
  license-notice:
    description: 'Custom license notice to be used if license is null'
    required: false
    default: null

outputs:
  issues: # id of output
    description: 'The list of files with header issues'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.owner }}
    - ${{ inputs.starting-year }}
    - ${{ inputs.license }}
    - ${{ inputs.folders }}
    - ${{ inputs.ignore-files }}
    - ${{ inputs.ignore-folders }}
    - ${{ inputs.license-notice }}
