name: Lint My Headers
author: frgfm
description: Check and safely update copyright and license headers in Python source files
branding:
  icon: check-square
  color: blue

inputs:
  owner:
    description: 'Name of the copyright owner; overrides pyproject.toml'
    required: false
    default: '__from_config__'
  starting-year:
    description: 'Starting year of your project; overrides pyproject.toml'
    required: false
    default: '__from_config__'
  license:
    # https://spdx.org/licenses/
    description: 'License of your project; overrides pyproject.toml'
    required: false
    default: '__from_config__'
  folders:
    description: 'Folders to inspect; overrides pyproject.toml'
    required: false
    default: '__from_config__'
  ignore-files:
    description: 'Files to ignore; overrides pyproject.toml'
    required: false
    default: '__from_config__'
  ignore-folders:
    description: 'Folders to ignore; overrides pyproject.toml'
    required: false
    default: '__from_config__'
  license-notice:
    description: 'Custom license notice; overrides pyproject.toml'
    required: false
    default: '__from_config__'
  mode:
    description: 'Whether to check or fix existing headers'
    required: false
    default: 'check'

outputs:
  issues:
    description: 'The list of files with header issues'
    value: ${{ steps.validate.outputs.issues }}
  changed:
    description: 'The list of files changed by fix mode'
    value: ${{ steps.validate.outputs.changed }}

runs:
  using: 'composite'
  steps:
    - name: Lint license headers
      id: validate
      shell: bash
      env:
        INPUT_OWNER: ${{ inputs.owner }}
        INPUT_STARTING_YEAR: ${{ inputs.starting-year }}
        INPUT_LICENSE: ${{ inputs.license }}
        INPUT_FOLDERS: ${{ inputs.folders }}
        INPUT_IGNORE_FILES: ${{ inputs.ignore-files }}
        INPUT_IGNORE_FOLDERS: ${{ inputs.ignore-folders }}
        INPUT_LICENSE_NOTICE: ${{ inputs.license-notice }}
        INPUT_MODE: ${{ inputs.mode }}
      run: |
        args=("$INPUT_MODE")
        if [[ "$INPUT_OWNER" != '__from_config__' ]]; then args+=(--owner "$INPUT_OWNER"); fi
        if [[ "$INPUT_STARTING_YEAR" != '__from_config__' ]]; then args+=(--starting-year "$INPUT_STARTING_YEAR"); fi
        if [[ "$INPUT_LICENSE" != '__from_config__' ]]; then args+=(--license "$INPUT_LICENSE"); fi
        if [[ "$INPUT_FOLDERS" != '__from_config__' ]]; then args+=(--folders "$INPUT_FOLDERS"); fi
        if [[ "$INPUT_IGNORE_FILES" != '__from_config__' ]]; then args+=(--ignore-files "$INPUT_IGNORE_FILES"); fi
        if [[ "$INPUT_IGNORE_FOLDERS" != '__from_config__' ]]; then args+=(--ignore-folders "$INPUT_IGNORE_FOLDERS"); fi
        if [[ "$INPUT_LICENSE_NOTICE" != '__from_config__' ]]; then args+=(--license-notice "$INPUT_LICENSE_NOTICE"); fi
        python "$GITHUB_ACTION_PATH/src/lint_my_headers/__main__.py" "${args[@]}"
