blank_issues_enabled: true
contact_links:
  - name: Usage questions
    url: https://github.com/frgfm/validate-python-headers/discussions
    about: Ask questions and discuss with other community members
